version: '3'
services:
  app:
    container_name: urano-php
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src/:/var/www/html
    ports:
      - "80:80"
    networks: 
      - portfolio 

  db1:
    container_name: urano-mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      # MySQLの設定ファイル
      - ./mysql/mysql_conf:/etc/mysql/conf.d
    networks: 
      - portfolio

networks:
    portfolio: